services:
  - type: web
    name: gamecheb-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn GameCheb.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamecheb-db

  - type: worker
    name: gamecheb-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamecheb-db

databases:
  - name: gamecheb-db
