databases:
  - name: questbot-db              # определяем базу данных PostgreSQL
    plan: free
    databaseName: questbot         # имя базы
    user: questbot
services:
  - type: web                      # веб-сервис для Django
    name: questbot-web
    runtime: python
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quest_bot.settings
      - key: SECRET_KEY
        generateValue: true        # сгенерировать SECRET_KEY автоматически
      - key: ALLOWED_HOSTS
        value: "questbot.onrender.com"   # ваш домен на Render
      - key: DATABASE_URL
        fromDatabase:
          name: questbot-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src/GameCheb
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quest_bot.wsgi:application --bind 0.0.0.0:$PORT

  - type: worker                   # фоновый процесс для Telegram-бота
    name: questbot-bot
    runtime: python
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quest_bot.settings
      - key: BOT_TOKEN
        value: "<YOUR_BOT_TOKEN>"  # задайте токен вашего бота
      - key: SECRET_KEY
        sync: true                 # взять то же значение, что и у web (можно через группу envVars)
      - key: DATABASE_URL
        fromDatabase:
          name: questbot-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src/GameCheb
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
