services:
  - type: web
    name: gamecheb-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quest_bot.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quest_bot.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres_8nu3_user:XCKx6lfQLSYW9ohMVwo0GSEg22pls1Hb@dpg-cvc0v7dsvqrc73aj7ag0-a/postgres_8nu3
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONPATH
        value: /opt/render/project/src/GameCheb
