databases:
  - name: gamecheb-db
    plan: free
    databaseName: gamecheb
    user: gamecheb

services:
  - type: web
    name: gamecheb-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quest_bot.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quest_bot.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
            name: gamecheb-db
            property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONPATH
        value: /opt/render/project/src/GameCheb

  - type: worker
    name: gamecheb-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quest_bot.settings
      - key: DATABASE_URL
        fromDatabase:
            name: gamecheb-db
            property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        value: 7214942810:AAErzQ5KjgzjA2qnSaX7s6_FFMGcrDgmZXc
      - key: PYTHONPATH
        value: /opt/render/project/src/GameCheb
